[book]
authors = ["Tyler Mandry"]
language = "en"
multilingual = false
src = "doc"
title = "Nimbus WM"

[output.html]
theme = "third_party/mdbook/theme"
additional-css = [
    "./third_party/catppuccin/catppuccin.css",
    "./third_party/catppuccin/catppuccin-alerts.css",
]
default-theme = "latte"
preferred-dark-theme = "mocha"
no-section-label = true

[output.html.print]
enable = false

[preprocessor.alerts]
